name: Build and Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cpp-build:
    name: Build C++ files
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install g++ 
        run: sudo apt-get update && sudo apt-get install -y g++ 

      - name: install python
        run: sudo apt-get update && sudo apt-get install -y python

      - name: build c++ files
        run: |
          find cpp -name "*.cpp" | while read file; do
            out_file="${file%.*}.out"
            g++ "$file" -o "$out_file"
          done
      - name: build python files
        run: |
          find python --name ".py" | while read file; do
            python "$file"
          done

